import {
  // Navigation Icons
  Home,
  Menu,
  X,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,

  // Business Icons
  Store,
  ShoppingCart,
  ShoppingBag,
  CreditCard,
  Package,
  MapPin,
  Phone,
  Mail,
  Clock,
  Calendar,
  Users,

  // Food & Restaurant Icons
  Coffee,
  Pizza,
  Utensils,
  ChefHat,
  Wine,
  Cookie,
  Apple,
  Cake,
  IceCream,
  Sandwich,

  // Social Media Icons
  Facebook,
  Instagram,
  Twitter,
  Linkedin,
  Youtube,
  MessageCircle,
  Share,
  Heart,
  ThumbsUp,

  // Interface Icons
  Settings,
  Search,
  Filter,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  AlertCircle,
  Info,
  Star,
  Eye,

  // Media Icons
  Play,
  Pause,
  Volume2,
  Image,
  Camera,
  Video,
  Download,
  Upload,
  File,
  Folder,

  // Weather & Nature Icons
  Sun,
  Moon,
  Cloud,
  CloudRain,
  Zap,
  Leaf,
  Flower,

  // Transport Icons
  Car,
  Truck,
  Plane,
  Ship,
  Bike,
  Bus,

  // Technology Icons
  Smartphone,
  Laptop,
  Monitor,
  Wifi,
  Battery,
  Globe,

  // Miscellaneous Icons
  Gift,
  Trophy,
  Medal,
  Flag,
  Bookmark,
  Tag,
  Lock,
  Unlock,
  Key,
  Shield,
  Bell,
  HelpCircle,
} from "lucide-react";

export const ICON_REGISTRY = {
  // Navigation
  home: {
    id: "home",
    name: "Home",
    component: Home,
    category: "navigation",
    tooltip: "Home page",
    keywords: ["home", "house", "main", "start"],
  },
  menu: {
    id: "menu",
    name: "Menu",
    component: Menu,
    category: "navigation",
    tooltip: "Menu toggle",
    keywords: ["menu", "hamburger", "navigation", "bars"],
  },
  close: {
    id: "close",
    name: "Close",
    component: X,
    category: "navigation",
    tooltip: "Close",
    keywords: ["close", "x", "cancel", "exit"],
  },
  arrowLeft: {
    id: "arrowLeft",
    name: "Arrow Left",
    component: ArrowLeft,
    category: "navigation",
    tooltip: "Previous",
    keywords: ["arrow", "left", "previous", "back"],
  },
  arrowRight: {
    id: "arrowRight",
    name: "Arrow Right",
    component: ArrowRight,
    category: "navigation",
    tooltip: "Next",
    keywords: ["arrow", "right", "next", "forward"],
  },
  chevronLeft: {
    id: "chevronLeft",
    name: "Chevron Left",
    component: ChevronLeft,
    category: "navigation",
    tooltip: "Previous",
    keywords: ["chevron", "left", "previous", "back"],
  },
  chevronRight: {
    id: "chevronRight",
    name: "Chevron Right",
    component: ChevronRight,
    category: "navigation",
    tooltip: "Next",
    keywords: ["chevron", "right", "next", "forward"],
  },

  // Business
  store: {
    id: "store",
    name: "Store",
    component: Store,
    category: "business",
    tooltip: "Store/Shop",
    keywords: ["store", "shop", "business", "retail"],
  },
  shoppingCart: {
    id: "shoppingCart",
    name: "Shopping Cart",
    component: ShoppingCart,
    category: "business",
    tooltip: "Shopping cart",
    keywords: ["cart", "shopping", "buy", "purchase"],
  },
  shoppingBag: {
    id: "shoppingBag",
    name: "Shopping Bag",
    component: ShoppingBag,
    category: "business",
    tooltip: "Shopping bag",
    keywords: ["bag", "shopping", "purchase", "buy"],
  },
  creditCard: {
    id: "creditCard",
    name: "Credit Card",
    component: CreditCard,
    category: "business",
    tooltip: "Payment",
    keywords: ["card", "payment", "credit", "money"],
  },
  mapPin: {
    id: "mapPin",
    name: "Location",
    component: MapPin,
    category: "business",
    tooltip: "Location",
    keywords: ["location", "pin", "address", "map"],
  },
  phone: {
    id: "phone",
    name: "Phone",
    component: Phone,
    category: "business",
    tooltip: "Phone number",
    keywords: ["phone", "call", "contact", "telephone"],
  },
  mail: {
    id: "mail",
    name: "Email",
    component: Mail,
    category: "business",
    tooltip: "Email",
    keywords: ["email", "mail", "message", "contact"],
  },
  clock: {
    id: "clock",
    name: "Clock",
    component: Clock,
    category: "business",
    tooltip: "Time/Hours",
    keywords: ["clock", "time", "hours", "schedule"],
  },
  calendar: {
    id: "calendar",
    name: "Calendar",
    component: Calendar,
    category: "business",
    tooltip: "Calendar/Date",
    keywords: ["calendar", "date", "schedule", "appointment"],
  },
  users: {
    id: "users",
    name: "Users",
    component: Users,
    category: "business",
    tooltip: "Users/Customers",
    keywords: ["users", "people", "customers", "team"],
  },

  // Food & Restaurant
  coffee: {
    id: "coffee",
    name: "Coffee",
    component: Coffee,
    category: "food",
    tooltip: "Coffee",
    keywords: ["coffee", "drink", "beverage", "cafe"],
  },
  pizza: {
    id: "pizza",
    name: "Pizza",
    component: Pizza,
    category: "food",
    tooltip: "Pizza",
    keywords: ["pizza", "food", "italian", "restaurant"],
  },
  utensils: {
    id: "utensils",
    name: "Utensils",
    component: Utensils,
    category: "food",
    tooltip: "Dining/Restaurant",
    keywords: ["utensils", "fork", "knife", "dining", "restaurant"],
  },
  chefHat: {
    id: "chefHat",
    name: "Chef Hat",
    component: ChefHat,
    category: "food",
    tooltip: "ChefHat/Kitchen",
    keywords: ["chef", "cook", "kitchen", "hat"],
  },
  wine: {
    id: "wine",
    name: "Wine",
    component: Wine,
    category: "food",
    tooltip: "Wine/Drinks",
    keywords: ["wine", "drink", "alcohol", "glass"],
  },

  // Social Media
  facebook: {
    id: "facebook",
    name: "Facebook",
    component: Facebook,
    category: "social",
    tooltip: "Facebook",
    keywords: ["facebook", "social", "media", "fb"],
  },
  instagram: {
    id: "instagram",
    name: "Instagram",
    component: Instagram,
    category: "social",
    tooltip: "Instagram",
    keywords: ["instagram", "social", "media", "photo"],
  },
  twitter: {
    id: "twitter",
    name: "Twitter",
    component: Twitter,
    category: "social",
    tooltip: "Twitter",
    keywords: ["twitter", "social", "media", "tweet"],
  },
  linkedin: {
    id: "linkedin",
    name: "LinkedIn",
    component: Linkedin,
    category: "social",
    tooltip: "LinkedIn",
    keywords: ["linkedin", "professional", "business", "network"],
  },
  youtube: {
    id: "youtube",
    name: "YouTube",
    component: Youtube,
    category: "social",
    tooltip: "YouTube",
    keywords: ["youtube", "video", "social", "media"],
  },
  heart: {
    id: "heart",
    name: "Heart",
    component: Heart,
    category: "social",
    tooltip: "Like/Favorite",
    keywords: ["heart", "like", "love", "favorite"],
  },

  // Interface
  settings: {
    id: "settings",
    name: "Settings",
    component: Settings,
    category: "interface",
    tooltip: "Settings",
    keywords: ["settings", "gear", "config", "options"],
  },
  search: {
    id: "search",
    name: "Search",
    component: Search,
    category: "interface",
    tooltip: "Search",
    keywords: ["search", "find", "magnify", "look"],
  },
  edit: {
    id: "edit",
    name: "Edit",
    component: Edit,
    category: "interface",
    tooltip: "Edit",
    keywords: ["edit", "pencil", "modify", "change"],
  },
  trash: {
    id: "trash",
    name: "Delete",
    component: Trash2,
    category: "interface",
    tooltip: "Delete",
    keywords: ["delete", "trash", "remove", "bin"],
  },
  plus: {
    id: "plus",
    name: "Add",
    component: Plus,
    category: "interface",
    tooltip: "Add/Create",
    keywords: ["add", "plus", "create", "new"],
  },
  check: {
    id: "check",
    name: "Check",
    component: Check,
    category: "interface",
    tooltip: "Success/Complete",
    keywords: ["check", "success", "complete", "done"],
  },
  star: {
    id: "star",
    name: "Star",
    component: Star,
    category: "interface",
    tooltip: "Favorite/Rating",
    keywords: ["star", "favorite", "rating", "review"],
  },

  // Miscellaneous
  gift: {
    id: "gift",
    name: "Gift",
    component: Gift,
    category: "misc",
    tooltip: "Gift/Present",
    keywords: ["gift", "present", "surprise", "box"],
  },
  bell: {
    id: "bell",
    name: "Notification",
    component: Bell,
    category: "misc",
    tooltip: "Notifications",
    keywords: ["bell", "notification", "alert", "ring"],
  },
  shield: {
    id: "shield",
    name: "Security",
    component: Shield,
    category: "misc",
    tooltip: "Security/Protection",
    keywords: ["shield", "security", "protect", "safe"],
  },
};

export const ICON_CATEGORIES = {
  navigation: "Navigation",
  business: "Business",
  food: "Food & Restaurant",
  social: "Social Media",
  interface: "Interface",
  misc: "Miscellaneous",
};

// Helper functions
export const getIconById = (id) => ICON_REGISTRY[id];
export const getIconsByCategory = (category) =>
  Object.values(ICON_REGISTRY).filter((icon) => icon.category === category);
export const searchIcons = (query) =>
  Object.values(ICON_REGISTRY).filter(
    (icon) =>
      icon.keywords.some((keyword) =>
        keyword.toLowerCase().includes(query.toLowerCase())
      ) || icon.name.toLowerCase().includes(query.toLowerCase())
  );
